const { createClient } = require('@supabase/supabase-js');

require('dotenv').config();

// Load SUPABASE_SERVICE_KEY from .env file
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_KEY;

// Create Supabase client instance
const supabase = createClient(supabaseUrl, supabaseKey, {
    auth: {
      autoRefreshToken: false,
      persistSession: false
    }
  });

let { user_all, user_admin, user_none, user_buildingsOnly, user_superadmin } = require('../acsense-tcd/assets/testObjects.js');
let { logs } = require('../acsense-tcd/assets/testObjects.js');

// Create the users
async function createUsers(users) {
    // Loop through the defined seed data above
    for (i = 0; i < users.length; i++) {
        // Create the user and auto-confirm
        const { data, error } = await supabase.auth.admin.createUser({
            email: users[i].email,
            password: "password123",
            email_confirm: true
          })

        if (error) {
            console.error(`Error creating user ${users[i].email}:`, error);
            break;
        } else {
            // console.log(`Created user ${users[i].email}`);
            process.stdout.write(`Created user [${i+1}/${users.length}](${users[i].email})                     \r`);
            // Log the new user ID so we can use it in the profiles table
            users[i].user_id = data.user.id;
        }
    }
    console.log(`[${i}/${users.length}] users created                         `);
}

async function createUserProfiles(users){

    for (i = 0; i < users.length; i++) {

        const { data, error } = await supabase
            .from('profiles')
            .insert(users[i])

        if (error) {
            console.error(`Error creating profile for ${users[i].email}:`, error);
            break;
        } else {
            // console.log(`Created profile for ${users[i].email}`);
            process.stdout.write(`Created profile [${i+1}/${users.length}](${users[i].email})                     \r`);
            // console.log(data)
        }
    }
    console.log(`[${i}/${users.length}] profiles created                         `);
}

function cleanUpTestProfiles(){
    // Process the profiles from the testObjects file 
    // Remove the fields that are not required
    // Return an array of appropriate profiles
    let users = [user_all, user_admin, user_none, user_buildingsOnly, user_superadmin];

    for (i = 0; i < users.length; i++) {
        // Remove the is_super_admin field as this is not stored in the profiles table
        if (users[i].hasOwnProperty('is_super_admin')) {
            delete users[i].is_super_admin;
        }
        // Remove the user_id field as this is generated by Supabase
        if (users[i].hasOwnProperty('user_id')) {
            delete users[i].is_super_admin;
        }
    }

    return users;
}

function cleanupLogs(){
    // Process the logs from the testObjects file 
    // Remove the fields that are not required
    // Return an array of appropriate logs
    let temp_logs = JSON.parse(JSON.stringify(logs));

    for (i = 0; i < logs.length; i++) {
        if (logs[i].hasOwnProperty('id')) {
            delete temp_logs[i].id;
        }
        if (logs[i].hasOwnProperty('created_at')) {
            delete temp_logs[i].created_at;
        }
        if (logs[i].hasOwnProperty('user')) {
            delete temp_logs[i].user;
        }
    }

    return temp_logs;
}

async function assignLogsToUsers(users, logs){

    // Loop through the logs and assign them to random users

    for (i = 0; i < logs.length; i++) {
        // Pick a random user
        let user = users[Math.floor(Math.random() * users.length)];
        logs[i].user = user.user_id;

        // Insert the log
        const {data, error} = await supabase
            .from('logs')
            .insert(logs[i])
            
            if(error){
                console.error(`Error inserting log ${i}/${logs.length} for user ${user.email}:`, error);
                // break;
                console.log("Retrying...");
                i--;
            }
    }

}

async function seed(){

    const users = cleanUpTestProfiles();

    await createUsers(users);
    await createUserProfiles(users);

    const log_templates = cleanupLogs();
    assignLogsToUsers(users, log_templates);
}

seed();