import type { Room_Template } from "../../acsense-tcd/assets/types/supabase_types";
require('dotenv').config();

let baseUrl = process.env.SUPABASE_URL || 'http://127.0.0.1:54321';

export default [
    {
      "building": "example-building-2",
      "room_code": "EX2ROOM1",
      "room_name": "EXAMPLE ROOM 2.1",
      "aka": "Ex room 1",
      "capacity": 22,
      "hearing_loop": false,
      "wheelchair": true,
      "outlets": false,
      "projector": true,
      "whiteboard": true,
      "lecturn": true,
      "room_type": "Flat",
    },
    {
      "building": "example-building-2",
      "room_code": "EX2ROOM10",
      "room_name": "EXAMPLE ROOM 2.10",
      "aka": "Ex room 10",
      "capacity": 75,
      "hearing_loop": true,
      "wheelchair": true,
      "outlets": true,
      "projector": true,
      "whiteboard": true,
      "lecturn": true,
      "room_type": "Tiered",
    },
    {
      "building": "example-building-2",
      "room_code": "EX2ROOM2",
      "room_name": "EXAMPLE ROOM 2.2",
      "aka": "Ex room 2",
      "capacity": 148,
      "hearing_loop": false,
      "wheelchair": false,
      "outlets": false,
      "projector": true,
      "whiteboard": true,
      "lecturn": true,
      "room_type": "Tiered",
    },
    {
      "building": "example-building-1",
      "room_code": "EX1ROOM3",
      "room_name": "EXAMPLE ROOM 1.3",
      "aka": "Ex room 3",
      "capacity": 35,
      "hearing_loop": false,
      "wheelchair": true,
      "outlets": true,
      "projector": true,
      "whiteboard": true,
      "lecturn": true,
      "room_type": "Lab",
    },
    {
      "building": "example-building-2",
      "room_code": "EX2ROOM8",
      "room_name": "EXAMPLE ROOM 2.8",
      "aka": "Ex room 8",
      "capacity": 90,
      "hearing_loop": true,
      "wheelchair": true,
      "outlets": true,
      "projector": true,
      "whiteboard": true,
      "lecturn": true,
      "room_type": "Flat",
    },
    {
      "building": "example-building-1",
      "room_code": "EX1ROOM2",
      "room_name": "EXAMPLE ROOM 1.2",
      "aka": "Ex room 2",
      "capacity": 148,
      "hearing_loop": false,
      "wheelchair": false,
      "outlets": false,
      "projector": true,
      "whiteboard": true,
      "lecturn": true,
      "room_type": "Tiered",
    },
    {
      "building": "example-building-1",
      "room_code": "EX1ROOM5",
      "room_name": "EXAMPLE ROOM 1.5",
      "aka": "Ex room 5",
      "capacity": 50,
      "hearing_loop": true,
      "wheelchair": true,
      "outlets": true,
      "projector": true,
      "whiteboard": true,
      "lecturn": true,
      "room_type": "Flat",
    },
    {
      "building": "example-building-2",
      "room_code": "EX2ROOM9",
      "room_name": "EXAMPLE ROOM 2.9",
      "aka": "Ex room 9",
      "capacity": 60,
      "hearing_loop": true,
      "wheelchair": true,
      "outlets": true,
      "projector": true,
      "whiteboard": true,
      "lecturn": true,
      "room_type": "Flat",
    },
    {
      "building": "example-building-2",
      "room_code": "EX2ROOM4",
      "room_name": "EXAMPLE ROOM 2.4",
      "aka": "Ex room 4",
      "capacity": 122,
      "hearing_loop": false,
      "wheelchair": true,
      "outlets": true,
      "projector": true,
      "whiteboard": true,
      "lecturn": true,
      "room_type": "Flat",
    },
    {
      "building": "example-building-2",
      "room_code": "EX2ROOM6",
      "room_name": "EXAMPLE ROOM 2.6",
      "aka": "Ex room 6",
      "capacity": 80,
      "hearing_loop": true,
      "wheelchair": true,
      "outlets": true,
      "projector": true,
      "whiteboard": true,
      "lecturn": true,
      "room_type": "Tiered",
    },
    {
      "building": "example-building-2",
      "room_code": "EX2ROOM7",
      "room_name": "EXAMPLE ROOM 2.7",
      "aka": "Ex room 7",
      "capacity": 30,
      "hearing_loop": false,
      "wheelchair": true,
      "outlets": true,
      "projector": true,
      "whiteboard": true,
      "lecturn": true,
      "room_type": "Lab",
    },
    {
      "building": "example-building-1",
      "room_code": "EX1ROOM6",
      "room_name": "EXAMPLE ROOM 1.6",
      "aka": "Ex room 6",
      "capacity": 80,
      "hearing_loop": true,
      "wheelchair": true,
      "outlets": true,
      "projector": true,
      "whiteboard": true,
      "lecturn": true,
      "room_type": "Tiered",
    },
    {
      "building": "example-building-2",
      "room_code": "EX2ROOM5",
      "room_name": "EXAMPLE ROOM 2.5",
      "aka": "Ex room 5",
      "capacity": 50,
      "hearing_loop": true,
      "wheelchair": true,
      "outlets": true,
      "projector": true,
      "whiteboard": true,
      "lecturn": true,
      "room_type": "Flat",
    },
    {
      "building": "example-building-2",
      "room_code": "EX2ROOM3",
      "room_name": "EXAMPLE ROOM 2.3",
      "aka": "Ex room 3",
      "capacity": 35,
      "hearing_loop": false,
      "wheelchair": true,
      "outlets": true,
      "projector": true,
      "whiteboard": true,
      "lecturn": true,
      "room_type": "Lab",
    },
    {
      "building": "example-building-1",
      "room_code": "EX1ROOM4",
      "room_name": "EXAMPLE ROOM 1.4",
      "aka": "Ex room 4",
      "capacity": 122,
      "hearing_loop": false,
      "wheelchair": true,
      "outlets": true,
      "projector": true,
      "whiteboard": true,
      "lecturn": true,
      "room_type": "Flat",
    },
    {
      "building": "example-building-1",
      "room_code": "EX1ROOM1",
      "room_name": "EXAMPLE ROOM 1.1",
      "aka": "Ex room 1",
      "capacity": 22,
      "hearing_loop": false,
      "wheelchair": true,
      "outlets": false,
      "projector": true,
      "whiteboard": true,
      "lecturn": true,
      "room_type": "Flat",
    },
    {
      "building": "example-building-1",
      "room_code": "EX1ROOM7",
      "room_name": "EXAMPLE ROOM 1.7",
      "aka": "Ex room 7",
      "capacity": 30,
      "hearing_loop": false,
      "wheelchair": true,
      "outlets": true,
      "projector": true,
      "whiteboard": true,
      "lecturn": true,
      "room_type": "Lab",
    },
    {
      "building": "example-building-1",
      "room_code": "EX1ROOM8",
      "room_name": "EXAMPLE ROOM 1.8",
      "aka": "Ex room 8",
      "capacity": 90,
      "hearing_loop": true,
      "wheelchair": true,
      "outlets": true,
      "projector": true,
      "whiteboard": true,
      "lecturn": true,
      "room_type": "Flat",
    }
  ] as Room_Template[];