export default [
    {
        "Name": "SU Kitchen",
        "location": "house-6",
        "type": "Social Space",
        "Description": "Kitchen available to all",
        "capacity": 0,
        "electrical_outlets": true,
        "food_drink_allowed": true,
        "indoors": true,
        "wheelchair_accessible": false,
        "kettle": true,
        "microwave": true,
        "coordinates": [53.34462, -6.25889 ],
        "url": "https://tcd-sense-map-assets.fra1.digitaloceanspaces.com/fada674505fcc8875fe2a99d47ca15b8.png",
    },
    {
        "Name": "College Health Respite Room",
        "location": "college-health",
        "type": "Respite Room",
        "Description": "The Respite Room can be accessed by asking the building receptionist for the keys, you can also book them online at https://www.tcd.ie/disability/support-and-resources/respite-space/",
        "capacity": 0,
        "electrical_outlets": true,
        "food_drink_allowed": false,
        "indoors": true,
        "wheelchair_accessible": true,
        "kettle": false,
        "microwave": false,
        "coordinates": [53.34501, -6.25536],
        "url": "https://tcd-sense-map-assets.fra1.digitaloceanspaces.com/b6a89a5c93184bc6c7ebfa4d9f1a3e95.png",
    },
    {
        "Name": "Wild Garden Seating",
        "location": "outdoors",
        "type": "Quiet Space",
        "Description": "This is located between College Park and the Rugby Pitch and has semi-circular seating for a small group.",
        "capacity": 4,
        "electrical_outlets": false,
        "food_drink_allowed": true,
        "indoors": false,
        "wheelchair_accessible": false,
        "kettle": false,
        "microwave": false,
        "coordinates": [53.34342, -6.252797 ],
        "url": "https://tcd-sense-map-assets.fra1.digitaloceanspaces.com/af336358b4f02d197667d15237723ff0.png",
    },
    {
        "Name": "Sports Centre Respite Room",
        "location": "sports-centre",
        "type": "Respite Room",
        "Description": "The Respite Room can be accessed by asking the building receptionist for the keys, you can also book them online at https://www.tcd.ie/disability/support-and-resources/respite-space/",
        "capacity": 0,
        "electrical_outlets": false,
        "food_drink_allowed": false,
        "indoors": true,
        "wheelchair_accessible": true,
        "kettle": false,
        "microwave": false,
        "coordinates": [53.34406, -6.25008 ],
        "url": "https://tcd-sense-map-assets.fra1.digitaloceanspaces.com/b6a89a5c93184bc6c7ebfa4d9f1a3e95.png",
    },
    {
        "Name": "AAP Cafe",
        "location": "aras-an-phiarsaigh",
        "type": "Social Space",
        "Description": "Small cafe with seating, coffee and snacks",
        "capacity": 0,
        "electrical_outlets": false,
        "food_drink_allowed": true,
        "indoors": true,
        "wheelchair_accessible": true,
        "kettle": false,
        "microwave": false,
        "coordinates": [53.34482, -6.25502 ],
        "url": "https://tcd-sense-map-assets.fra1.digitaloceanspaces.com/fada674505fcc8875fe2a99d47ca15b8.png",
    },
    {
        "Name": "Freeman Library",
        "location": "muesum-building",
        "type": "Study Space",
        "Description": "Library only available to Geo-sciences students",
        "capacity": 0,
        "electrical_outlets": false,
        "food_drink_allowed": false,
        "indoors": true,
        "wheelchair_accessible": false,
        "kettle": false,
        "microwave": false,
        "coordinates": [53.3439, -6.25507 ],
        "url": "https://tcd-sense-map-assets.fra1.digitaloceanspaces.com/890ea12ae6439456c7d985a0996d5beb.png",
    },
]