

export default [
    { 
        "time": "23/05/09 10:01",
        "user": "jane",
        "action": "create",
        "target": "arts-building",
        "field": "Building",
        "oldValue": null,
        "newValue": null,
    },
    {
        "time": "23/05/09 10:05",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "desc",
        "oldValue": "The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices.",
        "newValue": "The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices. There is a sensory space located at the rear of the building towards the lift that is bookable to students. The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },
    {
        "time": "23/05/09 10:09",
        "user": "jane",
        "action": "delete",
        "target": "arts-building",
        "field": "Building",
        "oldValue": null,
        "newValue": null
    },
    {
        "time": "23/05/09 10:11",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "lighting",
        "oldValue": "The lighting is bright and can be harsh at times.",
        "newValue": "The lighting is bright and can be harsh at times. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },{ 
        "time": "23/05/09 10:01",
        "user": "jane",
        "action": "create",
        "target": "arts-building",
        "field": "Building",
        "oldValue": null,
        "newValue": null,
    },
    {
        "time": "23/05/09 10:05",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "desc",
        "oldValue": "The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices.",
        "newValue": "The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },
    {
        "time": "23/05/09 10:09",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "sounds",
        "oldValue": "At busy times background noise, unpredictable noises, and where students gather for conversations.",
        "newValue": "At busy times background noise, unpredictable noises, and where students gather for conversations. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },
    {
        "time": "23/05/09 10:11",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "lighting",
        "oldValue": "The lighting is bright and can be harsh at times.",
        "newValue": "The lighting is bright and can be harsh at times. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },{ 
        "time": "23/05/09 10:01",
        "user": "jane",
        "action": "create",
        "target": "arts-building",
        "field": "Building",
        "oldValue": null,
        "newValue": null,
    },
    {
        "time": "23/05/09 10:05",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "desc",
        "oldValue": "The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices.",
        "newValue": "The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },
    {
        "time": "23/05/09 10:09",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "sounds",
        "oldValue": "At busy times background noise, unpredictable noises, and where students gather for conversations.",
        "newValue": "At busy times background noise, unpredictable noises, and where students gather for conversations. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },
    {
        "time": "23/05/09 10:11",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "lighting",
        "oldValue": "The lighting is bright and can be harsh at times.",
        "newValue": "The lighting is bright and can be harsh at times. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },{ 
        "time": "23/05/09 10:01",
        "user": "jane",
        "action": "create",
        "target": "arts-building",
        "field": "Building",
        "oldValue": null,
        "newValue": null,
    },
    {
        "time": "23/05/09 10:05",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "desc",
        "oldValue": "The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices.",
        "newValue": "The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },
    {
        "time": "23/05/09 10:09",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "sounds",
        "oldValue": "At busy times background noise, unpredictable noises, and where students gather for conversations.",
        "newValue": "At busy times background noise, unpredictable noises, and where students gather for conversations. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },
    {
        "time": "23/05/09 10:11",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "lighting",
        "oldValue": "The lighting is bright and can be harsh at times.",
        "newValue": "The lighting is bright and can be harsh at times. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },{ 
        "time": "23/05/09 10:01",
        "user": "jane",
        "action": "create",
        "target": "arts-building",
        "field": "Building",
        "oldValue": null,
        "newValue": null,
    },
    {
        "time": "23/05/09 10:05",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "desc",
        "oldValue": "The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices.",
        "newValue": "The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },
    {
        "time": "23/05/09 10:09",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "sounds",
        "oldValue": "At busy times background noise, unpredictable noises, and where students gather for conversations.",
        "newValue": "At busy times background noise, unpredictable noises, and where students gather for conversations. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },
    {
        "time": "23/05/09 10:11",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "lighting",
        "oldValue": "The lighting is bright and can be harsh at times.",
        "newValue": "The lighting is bright and can be harsh at times. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },{ 
        "time": "23/05/09 10:01",
        "user": "jane",
        "action": "create",
        "target": "arts-building",
        "field": "Building",
        "oldValue": null,
        "newValue": null,
    },
    {
        "time": "23/05/09 10:05",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "desc",
        "oldValue": "The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices.",
        "newValue": "The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },
    {
        "time": "23/05/09 10:09",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "sounds",
        "oldValue": "At busy times background noise, unpredictable noises, and where students gather for conversations.",
        "newValue": "At busy times background noise, unpredictable noises, and where students gather for conversations. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },
    {
        "time": "23/05/09 10:11",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "lighting",
        "oldValue": "The lighting is bright and can be harsh at times.",
        "newValue": "The lighting is bright and can be harsh at times. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },{ 
        "time": "23/05/09 10:01",
        "user": "jane",
        "action": "create",
        "target": "arts-building",
        "field": "Building",
        "oldValue": null,
        "newValue": null,
    },
    {
        "time": "23/05/09 10:05",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "desc",
        "oldValue": "The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices.",
        "newValue": "The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },
    {
        "time": "23/05/09 10:09",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "sounds",
        "oldValue": "At busy times background noise, unpredictable noises, and where students gather for conversations.",
        "newValue": "At busy times background noise, unpredictable noises, and where students gather for conversations. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },
    {
        "time": "23/05/09 10:11",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "lighting",
        "oldValue": "The lighting is bright and can be harsh at times.",
        "newValue": "The lighting is bright and can be harsh at times. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },{ 
        "time": "23/05/09 10:01",
        "user": "jane",
        "action": "create",
        "target": "arts-building",
        "field": "Building",
        "oldValue": null,
        "newValue": null,
    },
    {
        "time": "23/05/09 10:05",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "desc",
        "oldValue": "The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices.",
        "newValue": "The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },
    {
        "time": "23/05/09 10:09",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "sounds",
        "oldValue": "At busy times background noise, unpredictable noises, and where students gather for conversations.",
        "newValue": "At busy times background noise, unpredictable noises, and where students gather for conversations. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },
    {
        "time": "23/05/09 10:11",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "lighting",
        "oldValue": "The lighting is bright and can be harsh at times.",
        "newValue": "The lighting is bright and can be harsh at times. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },{ 
        "time": "23/05/09 10:01",
        "user": "jane",
        "action": "create",
        "target": "arts-building",
        "field": "Building",
        "oldValue": null,
        "newValue": null,
    },
    {
        "time": "23/05/09 10:05",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "desc",
        "oldValue": "The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices.",
        "newValue": "The Arts Building contains many large lecture theatres on the ground floor as well as seating areas and a coffee shop. There are a range of different department located on the upper floors along with various seminar rooms, classrooms and offices. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },
    {
        "time": "23/05/09 10:09",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "sounds",
        "oldValue": "At busy times background noise, unpredictable noises, and where students gather for conversations.",
        "newValue": "At busy times background noise, unpredictable noises, and where students gather for conversations. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },
    {
        "time": "23/05/09 10:11",
        "user": "jane",
        "action": "update",
        "target": "arts-building",
        "field": "lighting",
        "oldValue": "The lighting is bright and can be harsh at times.",
        "newValue": "The lighting is bright and can be harsh at times. There is a sensory space located at the rear of the building towards the lift that is bookable to students.",
    },

]