create table "public"."floorplans" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "building" uuid,
    "level" smallint,
    "label" text,
    "url" text
);


alter table "public"."floorplans" enable row level security;

alter table "public"."buildings" add column "entry_floor" smallint not null default '0'::smallint;

alter table "public"."buildings" add column "has_floorplan" boolean not null default false;

CREATE UNIQUE INDEX floorplans_pkey ON public.floorplans USING btree (id);

alter table "public"."floorplans" add constraint "floorplans_pkey" PRIMARY KEY using index "floorplans_pkey";

alter table "public"."floorplans" add constraint "floorplans_building_fkey" FOREIGN KEY (building) REFERENCES buildings("UUID") ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."floorplans" validate constraint "floorplans_building_fkey";

create policy "Enable insert for authenticated users only"
on "public"."floorplans"
as permissive
for all
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."floorplans"
as permissive
for select
to public
using (true);



