
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."building_gallery_images" (
    "id" bigint NOT NULL,
    "building" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "url" "text",
    "alt" "text",
    "caption" "text" DEFAULT ''::"text"
);

ALTER TABLE "public"."building_gallery_images" OWNER TO "postgres";

ALTER TABLE "public"."building_gallery_images" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."building_gallery_images_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."buildings" (
    "created_at" timestamp with time zone DEFAULT "now"(),
    "canonical" "text" DEFAULT 'building_url'::"text" NOT NULL,
    "display_name" "text" DEFAULT 'Building Name'::"text" NOT NULL,
    "aka" "text" DEFAULT 'aka'::"text",
    "map_label_1" "text",
    "map_label_2" "text",
    "map_label_3" "text",
    "geometry" "json" DEFAULT '{}'::"json" NOT NULL,
    "description" "text" DEFAULT ''::"text" NOT NULL,
    "sense_exp" "text" DEFAULT ''::"text",
    "wayfinding" "text" DEFAULT ''::"text",
    "phys_access" "text" DEFAULT ''::"text",
    "tips" "text"[] NOT NULL,
    "further_info" "text" DEFAULT ''::"text",
    "opening_times" "json",
    "sense_exp_display" boolean DEFAULT false NOT NULL,
    "phys_access_display" boolean DEFAULT false NOT NULL,
    "wayfinding_display" boolean DEFAULT false NOT NULL,
    "furtherinfo_display" boolean DEFAULT false NOT NULL,
    "primary_image_url" "text",
    "primary_image_alt" "text",
    "UUID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "always_display" boolean DEFAULT false,
    "sense_exp_video" "text",
    "wayfinding_video" "text",
    "phys_access_video" "text"
);

ALTER TABLE "public"."buildings" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."contributors" (
    "created_at" timestamp with time zone DEFAULT "now"(),
    "bld_general" boolean DEFAULT false NOT NULL,
    "bld_tabs" boolean DEFAULT false NOT NULL,
    "bld_gallery" boolean DEFAULT false NOT NULL,
    "sense_general" boolean DEFAULT false NOT NULL,
    "bld_map" boolean DEFAULT false NOT NULL,
    "email" character varying DEFAULT ''::character varying,
    "contributor_id" bigint NOT NULL,
    "bld_times" boolean DEFAULT false NOT NULL,
    "bld_tips" boolean DEFAULT false NOT NULL,
    "bld_further" boolean DEFAULT false NOT NULL,
    "sense_map" boolean DEFAULT false NOT NULL,
    "sense_facilities" boolean DEFAULT false NOT NULL,
    "sense_photos" boolean DEFAULT false NOT NULL
);

ALTER TABLE "public"."contributors" OWNER TO "postgres";

ALTER TABLE "public"."contributors" ALTER COLUMN "contributor_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."contributors_contributor_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."overlays" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "url" "text" DEFAULT '""'::"text" NOT NULL,
    "bounds" double precision[] DEFAULT '{{0,0},{0,0}}'::double precision[] NOT NULL
);

ALTER TABLE "public"."overlays" OWNER TO "postgres";

ALTER TABLE "public"."overlays" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."overlays_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."site_settings" (
    "id" bigint NOT NULL,
    "key" "text" NOT NULL,
    "data" "json" NOT NULL
);

ALTER TABLE "public"."site_settings" OWNER TO "postgres";

ALTER TABLE "public"."site_settings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."site_settings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."space_gallery_images" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "space" "uuid",
    "url" "text",
    "alt" "text",
    "caption" "text"
);

ALTER TABLE "public"."space_gallery_images" OWNER TO "postgres";

ALTER TABLE "public"."space_gallery_images" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."space_gallery_images_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."space_styles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "category" "text" NOT NULL,
    "icon" "text" NOT NULL,
    "colour" "text" DEFAULT '#ffffff'::"text",
    "descriptor" "text"
);

ALTER TABLE "public"."space_styles" OWNER TO "postgres";

ALTER TABLE "public"."space_styles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."space_styles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."spaces" (
    "name" "text" NOT NULL,
    "canonical" "text" NOT NULL,
    "description" "text" DEFAULT ''::"text" NOT NULL,
    "type" "text" DEFAULT ''::"text" NOT NULL,
    "last_updated" timestamp with time zone DEFAULT "now"() NOT NULL,
    "food_drink_allowed" boolean DEFAULT false NOT NULL,
    "microwave" boolean DEFAULT false NOT NULL,
    "kettle" boolean DEFAULT false NOT NULL,
    "wheelchair" boolean DEFAULT false NOT NULL,
    "location" double precision[] DEFAULT '{0,0}'::double precision[],
    "building" "text",
    "outlets" boolean DEFAULT false NOT NULL,
    "icon_override" "text",
    "seating" boolean DEFAULT false NOT NULL,
    "UUID" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "building_uuid" "uuid",
    "food_drink_allowed_note" "text" DEFAULT ''::"text" NOT NULL,
    "microwave_note" "text" DEFAULT ''::"text" NOT NULL,
    "kettle_note" "text" DEFAULT ''::"text" NOT NULL,
    "wheelchair_note" "text" DEFAULT ''::"text" NOT NULL,
    "seating_note" "text" DEFAULT ''::"text" NOT NULL,
    "outlets_note" "text" DEFAULT ''::"text" NOT NULL,
    "primary_image_url" "text",
    "primary_image_alt" "text",
    "tips" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "primary_image_panorama" boolean DEFAULT false NOT NULL,
    "sense_exp" "text" DEFAULT ''::"text" NOT NULL,
    "sense_exp_display" boolean DEFAULT false NOT NULL,
    "wayfinding" "text" DEFAULT ''::"text" NOT NULL,
    "wayfinding_display" boolean DEFAULT false NOT NULL,
    "phys_access" "text" DEFAULT ''::"text" NOT NULL,
    "phys_access_display" boolean DEFAULT false NOT NULL,
    "further_info" "text" DEFAULT ''::"text" NOT NULL,
    "further_info_display" boolean DEFAULT false NOT NULL,
    "aka" "text" DEFAULT ''::"text",
    "phys_access_video" "text",
    "sense_exp_video" "text",
    "wayfinding_video" "text"
);

ALTER TABLE "public"."spaces" OWNER TO "postgres";

ALTER TABLE ONLY "public"."building_gallery_images"
    ADD CONSTRAINT "building_gallery_images_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."buildings"
    ADD CONSTRAINT "buildings_canonical_key" UNIQUE ("canonical");

ALTER TABLE ONLY "public"."buildings"
    ADD CONSTRAINT "buildings_pkey" PRIMARY KEY ("UUID");

ALTER TABLE ONLY "public"."contributors"
    ADD CONSTRAINT "contributors_contributor_id_key" UNIQUE ("contributor_id");

ALTER TABLE ONLY "public"."contributors"
    ADD CONSTRAINT "contributors_pkey" PRIMARY KEY ("contributor_id");

ALTER TABLE ONLY "public"."overlays"
    ADD CONSTRAINT "overlays_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."site_settings"
    ADD CONSTRAINT "site_settings_key_key" UNIQUE ("key");

ALTER TABLE ONLY "public"."site_settings"
    ADD CONSTRAINT "site_settings_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."space_gallery_images"
    ADD CONSTRAINT "space_gallery_images_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."space_styles"
    ADD CONSTRAINT "space_styles_category_key" UNIQUE ("category");

ALTER TABLE ONLY "public"."space_styles"
    ADD CONSTRAINT "space_styles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."spaces"
    ADD CONSTRAINT "spaces_canonical_key" UNIQUE ("canonical");

ALTER TABLE ONLY "public"."spaces"
    ADD CONSTRAINT "spaces_pkey" PRIMARY KEY ("UUID");

ALTER TABLE ONLY "public"."building_gallery_images"
    ADD CONSTRAINT "building_gallery_images_building_fkey" FOREIGN KEY ("building") REFERENCES "public"."buildings"("canonical");

ALTER TABLE ONLY "public"."space_gallery_images"
    ADD CONSTRAINT "space_gallery_images_space_fkey" FOREIGN KEY ("space") REFERENCES "public"."spaces"("UUID") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."spaces"
    ADD CONSTRAINT "spaces_building_fkey" FOREIGN KEY ("building") REFERENCES "public"."buildings"("canonical");

ALTER TABLE ONLY "public"."spaces"
    ADD CONSTRAINT "spaces_building_uuid_fkey" FOREIGN KEY ("building_uuid") REFERENCES "public"."buildings"("UUID");

CREATE POLICY "Enable CRUD for authenticated users only" ON "public"."space_gallery_images" TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable delete access for all authenticated users" ON "public"."building_gallery_images" FOR DELETE TO "authenticated" USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."building_gallery_images" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."buildings" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."spaces" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON "public"."building_gallery_images" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."buildings" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."overlays" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."site_settings" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."space_gallery_images" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."space_styles" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."spaces" FOR SELECT USING (true);

CREATE POLICY "Enable select for authenticated users only" ON "public"."contributors" FOR SELECT TO "authenticated" USING (true);

CREATE POLICY "Enable update for authenticated users only" ON "public"."building_gallery_images" FOR UPDATE TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users only" ON "public"."buildings" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users only" ON "public"."overlays" FOR UPDATE TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users only" ON "public"."spaces" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);

ALTER TABLE "public"."building_gallery_images" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."buildings" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."contributors" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."overlays" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."site_settings" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."space_gallery_images" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."space_styles" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."spaces" ENABLE ROW LEVEL SECURITY;

REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."building_gallery_images" TO "anon";
GRANT ALL ON TABLE "public"."building_gallery_images" TO "authenticated";
GRANT ALL ON TABLE "public"."building_gallery_images" TO "service_role";

GRANT ALL ON SEQUENCE "public"."building_gallery_images_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."building_gallery_images_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."building_gallery_images_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."buildings" TO "anon";
GRANT ALL ON TABLE "public"."buildings" TO "authenticated";
GRANT ALL ON TABLE "public"."buildings" TO "service_role";

GRANT ALL ON TABLE "public"."contributors" TO "anon";
GRANT ALL ON TABLE "public"."contributors" TO "authenticated";
GRANT ALL ON TABLE "public"."contributors" TO "service_role";

GRANT ALL ON SEQUENCE "public"."contributors_contributor_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."contributors_contributor_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."contributors_contributor_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."overlays" TO "anon";
GRANT ALL ON TABLE "public"."overlays" TO "authenticated";
GRANT ALL ON TABLE "public"."overlays" TO "service_role";

GRANT ALL ON SEQUENCE "public"."overlays_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."overlays_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."overlays_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."site_settings" TO "anon";
GRANT ALL ON TABLE "public"."site_settings" TO "authenticated";
GRANT ALL ON TABLE "public"."site_settings" TO "service_role";

GRANT ALL ON SEQUENCE "public"."site_settings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."site_settings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."site_settings_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."space_gallery_images" TO "anon";
GRANT ALL ON TABLE "public"."space_gallery_images" TO "authenticated";
GRANT ALL ON TABLE "public"."space_gallery_images" TO "service_role";

GRANT ALL ON SEQUENCE "public"."space_gallery_images_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."space_gallery_images_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."space_gallery_images_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."space_styles" TO "anon";
GRANT ALL ON TABLE "public"."space_styles" TO "authenticated";
GRANT ALL ON TABLE "public"."space_styles" TO "service_role";

GRANT ALL ON SEQUENCE "public"."space_styles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."space_styles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."space_styles_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."spaces" TO "anon";
GRANT ALL ON TABLE "public"."spaces" TO "authenticated";
GRANT ALL ON TABLE "public"."spaces" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
