name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local development setup
        run: supabase db start

      - name: Verify generated types are checked in
        run: |
          supabase gen types typescript --local > acsense-tcd/assets/types/supabase_types.gen.ts
          if ! git diff --ignore-space-at-eol --exit-code --quiet acsense-tcd/assets/types/supabase_types.gen.ts; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi

  vitest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you are using

      - name: Move to the frontend directory
        run: cd acsense-tcd

      - name: Install dependencies
        run: npm install

      - name: Run Vitest
        run: npm run test